#### creating numpy array from list

In [2]:
import numpy as np

# 1D Array
arr = np.array([1, 2, 3, 4])
print(arr)  # Output: [1 2 3 4]

# 2D Array (Matrix)
matrix = np.array([[1, 2], [3, 4]])
print(matrix)  # Output: [[1 2] [3 4]]


[1 2 3 4]
[[1 2]
 [3 4]]


#### Creating Arrays with Predefined Values

In [3]:
arr_zeros = np.zeros((2, 3))  # 2x3 array of zeros
print(arr_zeros)


[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
arr_ones = np.ones((3, 2))  # 3x2 array of ones
print(arr_ones)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


##### Full: Creates an array filled with a specific value.


In [5]:
arr_full = np.full((2, 2), 7)  # 2x2 array filled with 7
print(arr_full)


[[7 7]
 [7 7]]


##### Eye: Creates an identity matrix (2D square array with ones on the diagonal).

In [6]:
identity = np.eye(4)  # 4x4 identity matrix
print(identity)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##### Random: Creates an array filled with random numbers.

In [7]:
random_arr = np.random.random((2, 3))  # 2x3 array of random floats between 0 and 1
print(random_arr)


[[0.23394716 0.11390032 0.57985943]
 [0.6295267  0.52580734 0.89324   ]]


##### Range: Creates an array with a specified range of values.

In [ ]:
arr_range = np.arange(0, 10, 2)  # Values from 0 to 10 with step 2
print(arr_range)


### NumPy `linspace` Function

The `np.linspace` function in NumPy is used to generate a sequence of evenly spaced values over a specified interval. It is often used when you need to create a set of values with a fixed number of steps, such as when plotting graphs or generating test data.

#### Syntax

```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)


In [8]:
import numpy as np

arr = np.linspace(0, 1, num=10)
print(arr)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


##### Array Properties

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Returns the dimensions (rows, columns)
print("Size:", arr.size)    # Total number of elements
print("Dimensions:", arr.ndim)  # Number of dimensions
print("Data Type:", arr.dtype)  # Data type of the array
print("Item Size:", arr.itemsize)  # Size in bytes of each element


Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int32
Item Size: 4


##### To declare a NumPy array with a specific data type, you can use the dtype parameter when creating the array. 

In [10]:
import numpy as np

arr = np.array([1.1, 2.2, 3.3, 4.4], dtype=int)
print(arr)
print(arr.dtype)


[1 2 3 4]
int32
