### Array indexing and slicing

##### Basic indexing

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])  # Access first element
print(arr[-1])  # Access last element


10
50


##### 2D Array Indexing

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d[0, 1])  # Access element at row 0, column 1
print(arr_2d[1, 2])  # Access element at row 1, column 2


2
6


- Indexing
     -  Indexing refers to accessing specific elements of a NumPy array, typically by specifying one or more indices (or positions) in the array. Indexing is used when you want to access a single element or a sub-array at specific locations.
- Slicing
     - Slicing, on the other hand, refers to accessing sub-arrays or a range of elements from a NumPy array. It allows you to create a view (or copy) of a portion of the original array, which can be useful for data manipulation and analysis.

Indexing refers to accessing specific elements or sub-arrays in an array using single or multiple indices, while slicing refers to accessing a contiguous range of elements or sub-arrays using a range of indices (start, stop, step).

##### 4.3. Slicing Arrays

In [4]:
# Slice from index 1 to 3
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # Output: [20 30 40]

# Slicing in 2D Arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[1:, 1:])  # Output: [[5 6] [8 9]]


[20 30 40]
[[5 6]
 [8 9]]


#####  Fancy Indexing
You can also use arrays of indices to index an array:

In [5]:
arr = np.array([1, 2, 3, 4, 5])
indices = [0, 2, 4]  # Select elements at indices 0, 2, and 4
print(arr[indices])  # Output: [1 3 5]


[1 3 5]
