##### Arithmetic Operations

In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # Element-wise addition
print(arr1 - arr2)  # Element-wise subtraction
print(arr1 * arr2)  # Element-wise multiplication
print(arr1 / arr2)  # Element-wise division


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


##### Scalar Operations

In [3]:
arr = np.array([1, 2, 3])
print(arr * 10)  # Multiply each element by 10


[10 20 30]


#####  Universal Functions (ufuncs)
- NumPy provides many ufuncs (universal functions) for performing operations efficiently on arrays:

In [4]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))  # Element-wise square root
print(np.log(arr))  # Element-wise logarithm
print(np.exp(arr))  # Element-wise exponential


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


#### Reshaping and Manipulating Arrays

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Reshape to 2x3 matrix
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


##### Transpose

In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.T)  # Transpose of the array


[[1 4]
 [2 5]
 [3 6]]


##### Flatten

In [7]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
flattened = arr_2d.flatten()  # Flatten the array
print(flattened)


[1 2 3 4 5 6]


####  Aggregation and Statistical Functions

- Aggregate functions are operations that take a set of values (or an array) and summarize or combine them into a single result, typically to perform some form of calculation like sum, mean, max, min, or count. These functions are commonly used in data analysis and statistics to condense large datasets into meaningful summaries.

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))  # Sum of elements
print(np.mean(arr))  # Mean (average) of elements
print(np.median(arr))  # Median of elements
print(np.std(arr))  # Standard deviation of elements


15
3.0
3.0
1.4142135623730951


##### Linear Algebra with NumPy

In [9]:
# Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)  # Matrix multiplication
# Alternatively:
result = matrix1 @ matrix2  # Same as above
print(result)


[[19 22]
 [43 50]]


##### matrix determinant

In [10]:
det = np.linalg.det(matrix1)
print(det)


-2.0000000000000004


####  Broadcasting

- Broadcasting is a powerful feature of NumPy that allows you to perform operations on arrays of different shapes. This happens automatically when NumPy can "stretch" one array to match the shape of another

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

print(arr1 + arr2)  # Broadcasting happens here


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [12]:
arr = np.array([1, 2, 3, 4])
scalar = 5
result = arr + scalar
print(result)


[6 7 8 9]


##### Adding a 1D Array to a 2D Array

In [13]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

# Broadcasting the 1D array over the 2D array
result = arr2d + arr1d
print(result)


[[11 22 33]
 [14 25 36]]


In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

# Broadcasting the 1D array over the 2D array
result = arr2d + arr1d
print(result)


[[11 22 33]
 [14 25 36]]


<b>Here, the 1D array [10, 20, 30] is broadcasted to each row of the 2D array.</b>This is equivalent to adding the array [10, 20, 30] to each row of the 2D array.

###  Masking and Boolean Indexing

In [16]:
arr = np.array([1, 2, 3, 4, 5])

# Get all elements greater than 2
print(arr[arr > 2])  # Output: [3 4 5]


[3 4 5]


In [18]:
arr > 2

array([False, False,  True,  True,  True])

- arr > 2 creates an array of the same shape as arr, but each element is either True or False, depending on whether the corresponding element in arr is greater than 2.

- Once you have a Boolean array like this, you can use it to index the original array and extract the elements that satisfy the condition

- <b>Masking in NumPy refers to the process of selecting or modifying elements in an array using a Boolean mask or Boolean array (often called a mask). The mask is an array of the same shape as the original array, where each element is either True or False. These True and False values determine which elements of the original array are included or modified in the operation.
</b>

###  Save and Load Arrays

In [19]:
np.save('array.npy', arr)  # Save array
loaded_arr = np.load('array.npy')  # Load array
print(loaded_arr)


[1 2 3 4 5]
