# Definitions of Random Modules in NumPy

## 1. **Basic Random Number Generation**
   - **`rand()`**: Generates random numbers from a uniform distribution over [0, 1).
   - **`randn()`**: Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
   - **`random()`**: Generates random floats from a uniform distribution over [0, 1).

## 2. **Discrete Distributions**
   - **`randint()`**: Generates random integers between low (inclusive) and high (exclusive).
   - **`binomial()`**: Draws samples from a binomial distribution.
   - **`poisson()`**: Draws samples from a Poisson distribution.
   - **`hypergeometric()`**: Draws samples from a hypergeometric distribution.
   - **`multinomial()`**: Generates samples from a multinomial distribution.
   - **`chisquare()`**: Draws samples from a chi-square distribution.
   - **`studentT()`**: Draws samples from a Student's t-distribution.

## 3. **Continuous Distributions**
   - **`uniform()`**: Generates random numbers from a uniform distribution over a given interval.
   - **`normal()`**: Draws samples from a normal (Gaussian) distribution with a given mean and standard deviation.
   - **`gamma()`**: Draws samples from a Gamma distribution.
   - **`exponential()`**: Draws samples from an exponential distribution.
   - **`beta()`**: Draws samples from a Beta distribution.
   - **`weibull()`**: Draws samples from a Weibull distribution.
   - **`dirichlet()`**: Draws samples from a Dirichlet distribution.
   - **`multivariate_normal()`**: Samples from a multivariate normal distribution.

## 4. **Shuffling and Permutation**
   - **`shuffle()`**: Randomly shuffles the elements of an array in place.
   - **`permutation()`**: Returns a permuted array or a randomly permuted sequence of numbers.

## 5. **Seed Control**
   - **`seed()`**: Sets the seed for random number generation to ensure reproducibility.
   - **`get_state()`**: Returns the state of the random number generator.
   - **`set_state()`**: Sets the state of the random number generator to a previously saved state.

## 6. **Random Sampling**
   - **`bytes()`**: Generates random bytes.



# Examples of Random Modules in NumPy

## 1. **Basic Random Number Generation**

```python
import numpy as np

# rand(): Generates random numbers from a uniform distribution over [0, 1).
print(np.random.rand(3, 2))

# randn(): Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
print(np.random.randn(3, 2))

# random(): Generates random floats from a uniform distribution over [0, 1).
print(np.random.random((2, 3)))


# 2. Discrete Distributions

In [11]:
import numpy as np
### randint(): Generates random integers between low (inclusive) and high (exclusive).
print(np.random.randint(1, 10, size=5))

### binomial(): Draws samples from a binomial distribution.
print(np.random.binomial(n=10, p=0.5, size=5))

### poisson(): Draws samples from a Poisson distribution.
print(np.random.poisson(lam=3.0, size=4))

### hypergeometric(): Draws samples from a hypergeometric distribution.
print(np.random.hypergeometric(ngood=5, nbad=10, nsample=5, size=3))

### multinomial(): Generates samples from a multinomial distribution.
print(np.random.multinomial(n=10, pvals=[0.2, 0.5, 0.3], size=2))

### chisquare(): Draws samples from a chi-square distribution.
print(np.random.chisquare(df=2, size=3))

### studentT(): Draws samples from a Student's t-distribution.
print(np.random.standard_t(df=10, size=3))


[1 8 2 3 8]
[5 6 5 9 3]
[3 2 4 1]
[3 1 1]
[[4 5 1]
 [2 3 5]]
[ 0.8331587   4.1185756  11.79272058]
[ 1.12989269 -1.22956256 -1.5819661 ]


### 3. Continuous Distributions

In [ ]:
# uniform(): Generates random numbers from a uniform distribution over a given interval.
print(np.random.uniform(low=0, high=1, size=5))

# normal(): Draws samples from a normal (Gaussian) distribution with a given mean and standard deviation.
print(np.random.normal(loc=0.0, scale=1.0, size=5))

# gamma(): Draws samples from a Gamma distribution.
print(np.random.gamma(shape=2.0, scale=2.0, size=3))

# exponential(): Draws samples from an exponential distribution.
print(np.random.exponential(scale=1.0, size=3))

# beta(): Draws samples from a Beta distribution.
print(np.random.beta(a=2.0, b=5.0, size=3))

# weibull(): Draws samples from a Weibull distribution.
print(np.random.weibull(a=1.5, size=3))

# dirichlet(): Draws samples from a Dirichlet distribution.
print(np.random.dirichlet(alpha=[0.2, 0.5, 0.3], size=3))

# multivariate_normal(): Samples from a multivariate normal distribution.
mean = [0, 0]
cov = [[1, 0], [0, 1]]
print(np.random.multivariate_normal(mean, cov, size=5))


### 4. Shuffling and Permutation


In [12]:
# shuffle(): Randomly shuffles the elements of an array in place.
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

# permutation(): Returns a permuted array or a randomly permuted sequence of numbers.
print(np.random.permutation(5))


[5 2 1 4 3]
[0 3 1 2 4]


### 5. Seed Control



In [13]:
# seed(): Sets the seed for random number generation to ensure reproducibility.
np.random.seed(42)
print(np.random.rand(2))

# get_state(): Returns the state of the random number generator.
state = np.random.get_state()

# set_state(): Sets the state of the random number generator to a previously saved state.
np.random.set_state(state)
print(np.random.rand(2))


[0.37454012 0.95071431]
[0.73199394 0.59865848]


### 6. Random Sampling

In [14]:
# bytes(): Generates random bytes.
print(np.random.bytes(10))


b'f\xd6\xf0\'y\x18"r\xd2A'
